name: Deploy
on:
    push:
        branches:
            - master
    repository_dispatch:

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
        - name: Deploy to staging server
          uses: AEnterprise/rsync-deploy@v1.0
          env:
              DEPLOY_KEY: ${{ secrets.SERVER_SSH_KEY }}
              ARGS: "-rltDzv --chown www-data:www-data --chmod=D666,F755"
              SERVER_PORT: ${{ secrets.SERVER_PORT }}
              FOLDER: "dist/"
              SERVER_IP: ${{ secrets.REMOTE_HOST }}
              USERNAME: ${{ secrets.REMOTE_USER }}
              SERVER_DESTINATION: ${{ secrets.REMOTE_TARGET }}
