name: Deploy
on:
    push:
        branches:
            - master
    repository_dispatch:

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout
          uses: actions/checkout@v2.0.0
        - name: Deploy to staging server
          uses: Pendect/action-rsyncer@v1.1.0
          env:
              DEPLOY_KEY: ${{ secrets.SERVER_SSH_KEY }}
          with:
              flags: "-rltDzv --chown www-data:www-data --chmod=D666,F755"
              options: ""
              src: "dist/"
              dest: ${{ secrets.DEST }}
